/**
 * Aggregated lifespan events from batch files.
 * Auto-generated by scripts/generate-lifespan-events.py
 */
import type { HistoricalEvent } from '@/lib/types';

import { _lifespanEventsBatch1 } from './_lifespanEventsBatch1';
import { _lifespanEventsBatch2 } from './_lifespanEventsBatch2';
import { _lifespanEventsBatch3 } from './_lifespanEventsBatch3';
import { _lifespanEventsBatch4 } from './_lifespanEventsBatch4';
import { _lifespanEventsBatch5 } from './_lifespanEventsBatch5';
import { _lifespanEventsBatch6 } from './_lifespanEventsBatch6';
import { _lifespanEventsBatch7 } from './_lifespanEventsBatch7';
import { _lifespanEventsBatch8 } from './_lifespanEventsBatch8';
import { _lifespanEventsBatch9 } from './_lifespanEventsBatch9';
import { _lifespanEventsBatch10 } from './_lifespanEventsBatch10';
import { _lifespanEventsBatch11 } from './_lifespanEventsBatch11';
import { _lifespanEventsBatch12 } from './_lifespanEventsBatch12';
import { _lifespanEventsBatch13 } from './_lifespanEventsBatch13';
import { _lifespanEventsBatch14 } from './_lifespanEventsBatch14';
import { _lifespanEventsBatch15 } from './_lifespanEventsBatch15';
import { _lifespanEventsBatch16 } from './_lifespanEventsBatch16';
import { _lifespanEventsBatch17 } from './_lifespanEventsBatch17';
import { _lifespanEventsBatch18 } from './_lifespanEventsBatch18';
import { _lifespanEventsBatch19 } from './_lifespanEventsBatch19';
import { _lifespanEventsBatch20 } from './_lifespanEventsBatch20';
import { _lifespanEventsBatch21 } from './_lifespanEventsBatch21';
import { _lifespanEventsBatch22 } from './_lifespanEventsBatch22';
import { _lifespanEventsBatch23 } from './_lifespanEventsBatch23';
import { _lifespanEventsBatch24 } from './_lifespanEventsBatch24';
import { _lifespanEventsBatch25 } from './_lifespanEventsBatch25';
import { _lifespanEventsBatch26 } from './_lifespanEventsBatch26';
import { _lifespanEventsBatch27 } from './_lifespanEventsBatch27';
import { _lifespanEventsBatch28 } from './_lifespanEventsBatch28';
import { _lifespanEventsBatch29 } from './_lifespanEventsBatch29';
import { _lifespanEventsBatch30 } from './_lifespanEventsBatch30';
import { _lifespanEventsBatch31 } from './_lifespanEventsBatch31';
import { _lifespanEventsBatch32 } from './_lifespanEventsBatch32';
import { _lifespanEventsBatch33 } from './_lifespanEventsBatch33';
import { _lifespanEventsBatch34 } from './_lifespanEventsBatch34';
import { _lifespanEventsBatch35 } from './_lifespanEventsBatch35';
import { _lifespanEventsBatch36 } from './_lifespanEventsBatch36';
import { _lifespanEventsBatch37 } from './_lifespanEventsBatch37';
import { _lifespanEventsBatch38 } from './_lifespanEventsBatch38';
import { _lifespanEventsBatch39 } from './_lifespanEventsBatch39';

export const allLifespanEvents = [
  ..._lifespanEventsBatch1,
  ..._lifespanEventsBatch2,
  ..._lifespanEventsBatch3,
  ..._lifespanEventsBatch4,
  ..._lifespanEventsBatch5,
  ..._lifespanEventsBatch6,
  ..._lifespanEventsBatch7,
  ..._lifespanEventsBatch8,
  ..._lifespanEventsBatch9,
  ..._lifespanEventsBatch10,
  ..._lifespanEventsBatch11,
  ..._lifespanEventsBatch12,
  ..._lifespanEventsBatch13,
  ..._lifespanEventsBatch14,
  ..._lifespanEventsBatch15,
  ..._lifespanEventsBatch16,
  ..._lifespanEventsBatch17,
  ..._lifespanEventsBatch18,
  ..._lifespanEventsBatch19,
  ..._lifespanEventsBatch20,
  ..._lifespanEventsBatch21,
  ..._lifespanEventsBatch22,
  ..._lifespanEventsBatch23,
  ..._lifespanEventsBatch24,
  ..._lifespanEventsBatch25,
  ..._lifespanEventsBatch26,
  ..._lifespanEventsBatch27,
  ..._lifespanEventsBatch28,
  ..._lifespanEventsBatch29,
  ..._lifespanEventsBatch30,
  ..._lifespanEventsBatch31,
  ..._lifespanEventsBatch32,
  ..._lifespanEventsBatch33,
  ..._lifespanEventsBatch34,
  ..._lifespanEventsBatch35,
  ..._lifespanEventsBatch36,
  ..._lifespanEventsBatch37,
  ..._lifespanEventsBatch38,
  ..._lifespanEventsBatch39,
] as HistoricalEvent[];
