-- ============================================
-- 事件去重 SQL v4 (精确年份匹配)
-- 共删除 140 条重复事件
-- 生成时间: 2026-06-20T11:29:02.209Z
-- ============================================

START TRANSACTION;

-- Batch 1 (100 events)
DELETE FROM event_persons WHERE event_id IN ('evt-struct3-dai-tian-ren-1899-实业家-extra','evt-struct3-wu-hua-1874-实业家-extra','evt-lifespan-he-qi-1859','evt-lifespan-何铸','evt-struct3-fu-fan-chu-1867-实业家-extra','evt-lifespan-元绛','evt-lifespan-元继','evt-lifespan-凌统','evt-struct3-liu-jin-yu-1898-实业家-extra','evt-lifespan-liu-jun-648','evt-struct3-zhou-jing-ting-1900-实业家-extra','evt-lifespan-周邦彦','evt-struct3-jiang-sheng-jie-1915-实业家-extra','evt-lifespan-子璇','evt-lifespan-孙翊','evt-lifespan-sun-ce-175','evt-lifespan-song-jiao-ren-1882','evt-lifespan-完颜秉德','evt-rich-tu-da-shan-1500-office10','evt-5c-cui-gui-cong-death','evt-rich-zuo-pei-1875-office11','evt-5c-yu-cheng-xuan-death','evt-lifespan-张仲景','evt-lifespan-张商英','evt-struct3-zhang-zhi-dong-1826-政治家-extra','evt-5c-xu-rong-death','evt-lifespan-xu-zi-hua-1873','evt-lifespan-折彦质','evt-lifespan-智圆','evt-lifespan-曹冲','evt-rich-zhu-dun-ru-1081-office8','evt-lifespan-李仁罕','evt-5c-li-yuan-gui-2-death','evt-5c-li-yuan-gui-death','evt-struct3-li-hua-1909-实业家-extra','evt-liqingzhao-early','evt-struct3-li-zhu-chen-1882-实业家-extra','evt-li-bai-major','evt-libai-enters-court','evt-libai-exiled-yelang','evt-lifespan-李继迁','evt-struct3-li-da-hai-1919-实业家-extra','evt-5c-li-qi-wu-death','evt-dufu-travels-wuyue','evt-dufu-trapped-anlushan','evt-liuzongyuan-exile','evt-lifespan-柳永','evt-lifespan-柳隐','evt-rich-yang-shi-cong-1597-office7','evt-lifespan-yang-shi-xiang-1860','evt-lifespan-yang-ying-ju-1696','evt-tsymq-0023','evt-rich-ouyang-xiu-exam','evt-rich-ouyang-xiu-office19','evt-lifespan-欧阳炯','evt-deep2-----7','evt-lifespan-wang-quan-1828','evt-rich-shen-mi-1501-office18','evt-lifespan-pan-gao-1514','evt-rich-pan-gao-1514-office9','evt-lifespan-王全斌','evt-deep5a-wang-da-li-613-death','evt-deep2-----0','evt-deep2-----1','evt-wang-anshi-reform','evt-songshenzong-reform','evt-lifespan-王安礼','evt-rich-wang-ju-zheng-1087-office3','evt-rich-wang-fen-1828-office0','evt-lifespan-wang-kai-yun-1832','evt-lifespan-richard-i','evt-lifespan-sheng-xuan-huai-1844','evt-lifespan-yu-zhi-mo-1866','evt-lifespan-qin-li-shan-1878','evt-struct3-qin-fen-1882-实业家-extra','evt-lifespan-章懿李皇后','evt-lifespan-章献皇后','evt-rich-mou-chang-qi-1562-office22','evt-struct3-luo-zhong-chen-1880-科学家-extra','evt-lifespan-耶律罨撤葛','evt-lifespan-耶律长寿女','evt-struct3-hu-xi-yuan-1900-实业家-extra','evt-su-shi-major','evt-sushi-wutai-trial','evt-wutai','evt-sushi-huangzhou','evt-sushi-lingnan','evt-struct3-su-song-政治家-extra','evt-fanzhongyan-reform','evt-fanzhongyan-yueyang','evt-struct3-fan-xu-dong-1883-实业家-extra','evt-struct3-sa-ben-xin-1898-实业家-extra','evt-rich-cai-bian-1058-office2','evt-lifespan-cai-e-1882','evt-rich-su-zhao-kui-1879-office20','evt-rich2-pei-ji-570-1','evt-lifespan-chu-jie-529','evt-lifespan-费士寅','evt-lifespan-赵明诚','evt-lifespan-赵禼');
DELETE FROM events WHERE id IN ('evt-struct3-dai-tian-ren-1899-实业家-extra','evt-struct3-wu-hua-1874-实业家-extra','evt-lifespan-he-qi-1859','evt-lifespan-何铸','evt-struct3-fu-fan-chu-1867-实业家-extra','evt-lifespan-元绛','evt-lifespan-元继','evt-lifespan-凌统','evt-struct3-liu-jin-yu-1898-实业家-extra','evt-lifespan-liu-jun-648','evt-struct3-zhou-jing-ting-1900-实业家-extra','evt-lifespan-周邦彦','evt-struct3-jiang-sheng-jie-1915-实业家-extra','evt-lifespan-子璇','evt-lifespan-孙翊','evt-lifespan-sun-ce-175','evt-lifespan-song-jiao-ren-1882','evt-lifespan-完颜秉德','evt-rich-tu-da-shan-1500-office10','evt-5c-cui-gui-cong-death','evt-rich-zuo-pei-1875-office11','evt-5c-yu-cheng-xuan-death','evt-lifespan-张仲景','evt-lifespan-张商英','evt-struct3-zhang-zhi-dong-1826-政治家-extra','evt-5c-xu-rong-death','evt-lifespan-xu-zi-hua-1873','evt-lifespan-折彦质','evt-lifespan-智圆','evt-lifespan-曹冲','evt-rich-zhu-dun-ru-1081-office8','evt-lifespan-李仁罕','evt-5c-li-yuan-gui-2-death','evt-5c-li-yuan-gui-death','evt-struct3-li-hua-1909-实业家-extra','evt-liqingzhao-early','evt-struct3-li-zhu-chen-1882-实业家-extra','evt-li-bai-major','evt-libai-enters-court','evt-libai-exiled-yelang','evt-lifespan-李继迁','evt-struct3-li-da-hai-1919-实业家-extra','evt-5c-li-qi-wu-death','evt-dufu-travels-wuyue','evt-dufu-trapped-anlushan','evt-liuzongyuan-exile','evt-lifespan-柳永','evt-lifespan-柳隐','evt-rich-yang-shi-cong-1597-office7','evt-lifespan-yang-shi-xiang-1860','evt-lifespan-yang-ying-ju-1696','evt-tsymq-0023','evt-rich-ouyang-xiu-exam','evt-rich-ouyang-xiu-office19','evt-lifespan-欧阳炯','evt-deep2-----7','evt-lifespan-wang-quan-1828','evt-rich-shen-mi-1501-office18','evt-lifespan-pan-gao-1514','evt-rich-pan-gao-1514-office9','evt-lifespan-王全斌','evt-deep5a-wang-da-li-613-death','evt-deep2-----0','evt-deep2-----1','evt-wang-anshi-reform','evt-songshenzong-reform','evt-lifespan-王安礼','evt-rich-wang-ju-zheng-1087-office3','evt-rich-wang-fen-1828-office0','evt-lifespan-wang-kai-yun-1832','evt-lifespan-richard-i','evt-lifespan-sheng-xuan-huai-1844','evt-lifespan-yu-zhi-mo-1866','evt-lifespan-qin-li-shan-1878','evt-struct3-qin-fen-1882-实业家-extra','evt-lifespan-章懿李皇后','evt-lifespan-章献皇后','evt-rich-mou-chang-qi-1562-office22','evt-struct3-luo-zhong-chen-1880-科学家-extra','evt-lifespan-耶律罨撤葛','evt-lifespan-耶律长寿女','evt-struct3-hu-xi-yuan-1900-实业家-extra','evt-su-shi-major','evt-sushi-wutai-trial','evt-wutai','evt-sushi-huangzhou','evt-sushi-lingnan','evt-struct3-su-song-政治家-extra','evt-fanzhongyan-reform','evt-fanzhongyan-yueyang','evt-struct3-fan-xu-dong-1883-实业家-extra','evt-struct3-sa-ben-xin-1898-实业家-extra','evt-rich-cai-bian-1058-office2','evt-lifespan-cai-e-1882','evt-rich-su-zhao-kui-1879-office20','evt-rich2-pei-ji-570-1','evt-lifespan-chu-jie-529','evt-lifespan-费士寅','evt-lifespan-赵明诚','evt-lifespan-赵禼');

-- Batch 2 (40 events)
DELETE FROM event_persons WHERE event_id IN ('evt-rich-zhao-fan-1851-office6','evt-lifespan-邓洵武','evt-struct3-guo-xu-zhong-1912-实业家-extra','evt-lifespan-shi-shao-zong-1074','evt-lifespan-qian-hong-xuan-913','evt-lifespan-zhong-yao-151','evt-lifespan-钱传璛','evt-lifespan-钱传璟','evt-lifespan-钱元懿','evt-lifespan-钱元珦','evt-lifespan-钱元珰','evt-lifespan-钱元球','evt-lifespan-钱元璙','evt-lifespan-钱元璲','evt-lifespan-钱元瞿','evt-lifespan-钱弘仪','evt-lifespan-钱弘仰','evt-lifespan-钱弘偓','evt-lifespan-钱弘偡','evt-lifespan-钱弘僔','evt-lifespan-钱弘儇','evt-lifespan-钱惟演','evt-lifespan-钱惟濬','evt-lifespan-钱景臻','evt-5c-zhang-sun-wu-ji-death','evt-lifespan-ruan-xing-cun-1874','evt-lifespan-陆知命','evt-lifespan-陈洪进','evt-lifespan-chen-you-liang-1320','evt-struct3-chen-shang-wen-1897-实业家-extra','evt-lifespan-韦敻','evt-tsymq-0010','evt-lifespan-gu-yong-168','evt-lifespan-颜之推','evt-lifespan-马绰','evt-lifespan-鲁肃','evt-struct3-huang-ya-fu-1837-实业家-extra','evt-lifespan-黄居采','evt-lifespan-黄荃','evt-lifespan-龚美');
DELETE FROM events WHERE id IN ('evt-rich-zhao-fan-1851-office6','evt-lifespan-邓洵武','evt-struct3-guo-xu-zhong-1912-实业家-extra','evt-lifespan-shi-shao-zong-1074','evt-lifespan-qian-hong-xuan-913','evt-lifespan-zhong-yao-151','evt-lifespan-钱传璛','evt-lifespan-钱传璟','evt-lifespan-钱元懿','evt-lifespan-钱元珦','evt-lifespan-钱元珰','evt-lifespan-钱元球','evt-lifespan-钱元璙','evt-lifespan-钱元璲','evt-lifespan-钱元瞿','evt-lifespan-钱弘仪','evt-lifespan-钱弘仰','evt-lifespan-钱弘偓','evt-lifespan-钱弘偡','evt-lifespan-钱弘僔','evt-lifespan-钱弘儇','evt-lifespan-钱惟演','evt-lifespan-钱惟濬','evt-lifespan-钱景臻','evt-5c-zhang-sun-wu-ji-death','evt-lifespan-ruan-xing-cun-1874','evt-lifespan-陆知命','evt-lifespan-陈洪进','evt-lifespan-chen-you-liang-1320','evt-struct3-chen-shang-wen-1897-实业家-extra','evt-lifespan-韦敻','evt-tsymq-0010','evt-lifespan-gu-yong-168','evt-lifespan-颜之推','evt-lifespan-马绰','evt-lifespan-鲁肃','evt-struct3-huang-ya-fu-1837-实业家-extra','evt-lifespan-黄居采','evt-lifespan-黄荃','evt-lifespan-龚美');

COMMIT;

-- Verify:
-- SELECT COUNT(*) as remaining FROM events WHERE data_status = 'published';