#!/usr/bin/env python3
"""Generate new source entries for ruler data."""
print("""  {
    id: 'src-shiji',
    title: '《史记》',
    titleEn: 'Records of the Grand Historian (Shiji)',
    author: '司马迁',
    year: -91,
    note: '中国第一部纪传体通史，涵盖黄帝至汉武帝时期。',
    license: 'Public Domain',
  },
  {
    id: 'src-hanshu',
    title: '《汉书》',
    titleEn: 'Book of Han (Hanshu)',
    author: '班固',
    year: 111,
    note: '中国第一部断代史，记录西汉历史。',
    license: 'Public Domain',
  },
  {
    id: 'src-sanguozhi',
    title: '《三国志》',
    titleEn: 'Records of the Three Kingdoms (Sanguozhi)',
    author: '陈寿',
    year: 289,
    note: '记载魏蜀吴三国历史的纪传体史书。',
    license: 'Public Domain',
  },
  {
    id: 'src-suisheshu',
    title: '《隋书》',
    titleEn: 'Book of Sui (Suishu)',
    author: '魏徵等',
    year: 636,
    note: '二十四史之一，记录隋朝历史。',
    license: 'Public Domain',
  },
  {
    id: 'src-jiutangshu',
    title: '《旧唐书》',
    titleEn: 'Old Book of Tang (Jiu Tangshu)',
    author: '刘昫等',
    year: 945,
    note: '记录唐朝历史的官修史书。',
    license: 'Public Domain',
  },
  {
    id: 'src-yuanshi',
    title: '《元史》',
    titleEn: 'History of Yuan (Yuanshi)',
    author: '宋濂等',
    year: 1370,
    note: '明朝官修的元朝正史。',
    license: 'Public Domain',
  },
  {
    id: 'src-mingshi',
    title: '《明史》',
    titleEn: 'History of Ming (Mingshi)',
    author: '张廷玉等',
    year: 1739,
    note: '清朝官修的明朝正史，二十四史中修撰时间最长的一部。',
    license: 'Public Domain',
  },
  {
    id: 'src-qingshigao',
    title: '《清史稿》',
    titleEn: 'Draft History of Qing (Qingshigao)',
    author: '赵尔巽等',
    year: 1928,
    note: '清朝历史的纪传体史书未定稿。',
    license: 'Public Domain',
  },
  {
    id: 'src-plutarch',
    title: '《希腊罗马名人传》',
    titleEn: 'Parallel Lives (Plutarch)',
    author: 'Plutarch',
    year: 100,
    note: '普鲁塔克所著希腊罗马名人传记集。',
    license: 'Public Domain',
  },
  {
    id: 'src-tacitus',
    title: '《编年史》',
    titleEn: 'Annals (Tacitus)',
    author: 'Tacitus',
    year: 117,
    note: '塔西佗所著罗马帝国早期历史。',
    license: 'Public Domain',
  },
  {
    id: 'src-suetonius',
    title: '《罗马十二帝王传》',
    titleEn: 'The Twelve Caesars (Suetonius)',
    author: 'Suetonius',
    year: 121,
    note: '苏埃托尼乌斯所著凯撒至图密善的罗马帝王传记。',
    license: 'Public Domain',
  },
  {
    id: 'src-procopius',
    title: '《战史》',
    titleEn: 'History of the Wars (Procopius)',
    author: 'Procopius',
    year: 554,
    note: '普罗柯比记录查士丁尼时期战争与宫廷的著作。',
    license: 'Public Domain',
  },
  {
    id: 'src-asc',
    title: '《盎格鲁-撒克逊编年史》',
    titleEn: 'Anglo-Saxon Chronicle',
    year: 891,
    note: '记录盎格鲁-撒克逊时期英格兰历史的编年体文献。',
    license: 'Public Domain',
  },
  {
    id: 'src-illuminated',
    title: '《插图史记》',
    titleEn: 'Grandes Chroniques de France',
    year: 1274,
    note: '法兰西王国官方编年史，记录卡佩等王朝历史。',
    license: 'Public Domain',
  },
  {
    id: 'src-akbarnama',
    title: '《阿克巴本纪》',
    titleEn: 'Akbarnama',
    author: 'Abul Fazl',
    year: 1596,
    note: '莫卧儿帝国阿克巴大帝的官方传记。',
    license: 'Public Domain',
  },
""")
