#!/usr/bin/env python3
"""Generate new regions for dynasties and countries needed by rulers data."""
print("""  {
    id: 'qin-dynasty',
    name: '秦朝',
    nameEn: 'Qin Dynasty',
    slug: 'qin-dynasty',
    parentRegionId: 'china',
    description: '前221年—前206年，中国历史上第一个大一统帝国。',
    descriptionEn: '221–206 BCE. The first unified imperial dynasty in Chinese history.',
  },
  {
    id: 'han-dynasty',
    name: '汉朝',
    nameEn: 'Han Dynasty',
    slug: 'han-dynasty',
    parentRegionId: 'china',
    description: '前202年—220年，继秦之后的大一统王朝，分西汉和东汉，华夏文明的关键定型期。',
    descriptionEn: '202 BCE–220 CE. The unified dynasty after Qin, divided into Western and Eastern Han, the defining era of Chinese civilization.',
  },
  {
    id: 'sui-dynasty',
    name: '隋朝',
    nameEn: 'Sui Dynasty',
    slug: 'sui-dynasty',
    parentRegionId: 'china',
    description: '581年—618年，结束南北朝分裂的统一王朝，开创科举制度和开凿大运河。',
    descriptionEn: '581–618. The dynasty that reunified China after the Northern and Southern period, establishing the imperial examination and the Grand Canal.',
  },
  {
    id: 'yuan-dynasty',
    name: '元朝',
    nameEn: 'Yuan Dynasty',
    slug: 'yuan-dynasty',
    parentRegionId: 'china',
    description: '1271年—1368年，蒙古人建立的统一王朝，疆域辽阔，东西方交流空前活跃。',
    descriptionEn: '1271–1368. The Mongol-established dynasty with vast territory and unprecedented East-West exchange.',
  },
  {
    id: 'qing-dynasty',
    name: '清朝',
    nameEn: 'Qing Dynasty',
    slug: 'qing-dynasty',
    parentRegionId: 'china',
    description: '1644年—1912年，中国最后一个封建王朝，由满族建立，经历康乾盛世与近代变局。',
    descriptionEn: '1644–1912. China's last imperial dynasty, established by the Manchus, experiencing the High Qing era and modern upheavals.',
  },
  {
    id: 'three-kingdoms',
    name: '三国',
    nameEn: 'Three Kingdoms',
    slug: 'three-kingdoms',
    parentRegionId: 'china',
    description: '220年—280年，魏蜀吴三国鼎立的分裂时期，英雄辈出的传奇时代。',
    descriptionEn: '220–280. The tripartite division of Wei, Shu, and Wu, a legendary era of heroes and strategists.',
  },
  {
    id: 'france',
    name: '法兰西',
    nameEn: 'France',
    slug: 'france',
    parentRegionId: 'europe',
    description: '从中世纪法兰克王国延续至现代的法兰西，涵盖卡佩、瓦卢瓦、波旁等王朝。',
    descriptionEn: 'From medieval Francia to modern France, spanning Capetian, Valois, Bourbon, and later eras.',
  },
  {
    id: 'russia',
    name: '俄罗斯',
    nameEn: 'Russia',
    slug: 'russia',
    parentRegionId: 'europe',
    description: '从基辅罗斯到莫斯科大公国、沙皇俄国及俄罗斯帝国。',
    descriptionEn: 'From Kievan Rus to the Grand Duchy of Moscow, Tsardom, and the Russian Empire.',
  },
  {
    id: 'ottoman-empire',
    name: '奥斯曼帝国',
    nameEn: 'Ottoman Empire',
    slug: 'ottoman-empire',
    parentRegionId: 'middle-east',
    description: '1299年—1922年，横跨欧亚非的伊斯兰帝国，延续六个多世纪。',
    descriptionEn: '1299–1922. An Islamic empire spanning Europe, Asia, and Africa for over six centuries.',
  },
  {
    id: 'persia',
    name: '波斯',
    nameEn: 'Persia',
    slug: 'persia',
    parentRegionId: 'middle-east',
    description: '从阿契美尼德王朝到萨珊帝国，伊朗高原上的古代文明中心。',
    descriptionEn: 'From the Achaemenid dynasty to the Sassanian Empire, the ancient civilizational center of the Iranian plateau.',
  },
  {
    id: 'korea',
    name: '朝鲜',
    nameEn: 'Korea',
    slug: 'korea',
    parentRegionId: 'asia',
    description: '从三国时代到高丽、朝鲜王朝的朝鲜半岛历史。',
    descriptionEn: 'From the Three Kingdoms period through Goryeo and Joseon dynasties on the Korean Peninsula.',
  },
  {
    id: 'egypt',
    name: '古埃及',
    nameEn: 'Ancient Egypt',
    slug: 'egypt',
    parentRegionId: 'africa',
    description: '尼罗河畔的古代文明，从前王朝时期到托勒密王朝，延续三千余年。',
    descriptionEn: 'The ancient civilization along the Nile, from the Predynastic period to the Ptolemaic dynasty, spanning over 3,000 years.',
  },
  {
    id: 'holy-roman-empire',
    name: '神圣罗马帝国',
    nameEn: 'Holy Roman Empire',
    slug: 'holy-roman-empire',
    parentRegionId: 'europe',
    description: '962年—1806年，覆盖中欧的封建帝国，由选帝侯选举皇帝。',
    descriptionEn: '962–1806. A feudal empire covering Central Europe, with emperors elected by prince-electors.',
  },
  {
    id: 'safavid-persia',
    name: '萨法维波斯',
    nameEn: 'Safavid Persia',
    slug: 'safavid-persia',
    parentRegionId: 'middle-east',
    description: '1501年—1736年，波斯第三个伊斯兰化帝国，确立了什叶派为国教。',
    descriptionEn: '1501–1736. The third Islamized Persian empire, establishing Shia Islam as the state religion.',
  },
  {
    id: 'aztec-empire',
    name: '阿兹特克帝国',
    nameEn: 'Aztec Empire',
    slug: 'aztec-empire',
    parentRegionId: 'americas',
    description: '1428年—1521年，中美洲的强大帝国，以特诺奇蒂特兰为中心。',
    descriptionEn: '1428–1521. A powerful Mesoamerican empire centered on Tenochtitlan.',
  },
  {
    id: 'inca-empire',
    name: '印加帝国',
    nameEn: 'Inca Empire',
    slug: 'inca-empire',
    parentRegionId: 'americas',
    description: '1438年—1533年，南美洲安第斯山脉的前哥伦布时期最大帝国。',
    descriptionEn: '1438–1533. The largest pre-Columbian empire in the Andes of South America.',
  },
  {
    id: 'united-states',
    name: '美利坚合众国',
    nameEn: 'United States',
    slug: 'united-states',
    parentRegionId: 'americas',
    description: '1776年建立，经过独立战争和西进运动，成为20世纪超级大国。',
    descriptionEn: 'Founded in 1776, the United States grew through independence, westward expansion, and emerged as a 20th-century superpower.',
  },
""")
